# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # create some web servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..2).each do |i|
    config.vm.define "gluster#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "gluster#{i}"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
    end
  end


end
